### ISSUE TITLE
DMA_Plantuml.cpp: error C2039: 'tolower': is not a member of 'std'

### ISSUE THREAD

**Issue by jschmer** [svlad-90/DMA_Plantuml#17]
**Describe the bug**
Compile error on Windows as part svlad-90/DLT-Message-Analyzer:
```
[ 45%] Building CXX object _deps/dma_plantuml-build/DMA_Plantuml/src/CMakeFiles/DMA_Plantuml.dir/DMA_Plantuml.cpp.obj
DMA_Plantuml.cpp
E:\Repo\dlt-viewer\build-cmake-nmake\_deps\dma_plantuml-src\DMA_Plantuml\src\DMA_Plantuml.cpp(968): error C2039: 'tolower': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\include\mutex(26): note: see declaration of 'std'
E:\Repo\dlt-viewer\build-cmake-nmake\_deps\dma_plantuml-src\DMA_Plantuml\src\DMA_Plantuml.cpp(978): error C2039: 'tolower': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\include\mutex(26): note: see declaration of 'std'
```

**To Reproduce**
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
WindowsSDKVersion=10.0.19041.0\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\
VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023\
VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.29.30133\
VCToolsVersion=14.16.27023

My environment uses Windows SDK version 10.0.19041.0 and MSVC compiler version 14.16 (VS 2017) with Qt5.14.2

**Expected behavior**
Code compiles without errors

**Comment by jschmer** [comment]
According to https://en.cppreference.com/w/cpp/string/byte/tolower std::tolower is defined in header \<cctype>

**Comment by svlad-90** [comment]
Hi @jschmer, first of all, thanks for creating this issue and for providing an extensive description of it. 

I've created a PR which will, probably, help you to step over the build failure - https://github.com/svlad-90/DMA_Plantuml/pull/18

Still, I don't have enough time to set up the same environment, which you have. Could you, please, try it out yourself?

I've merged the PR. Just try to rebuild the DMA plugin and it should fetch the head version of the DMA_Plantuml project.

If the fix won't help - let me know which errors you have after the application of the fix, and I'll continue the investigation.

**Comment by jschmer** [comment]
Thank you! I can confirm this builds without errors now in my environment.

**Comment by svlad-90** [comment]
Hi @jschmer, great! 

Thanks for the confirmation.
